# Generated by Django 5.1.5 on 2025-02-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='numero_particular',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
