# Generated by Django 5.1.5 on 2025-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_propiedad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
